export const data = [
    {
      id: 1,
      name: 'Vegetables',
      image: require('./images/vegetables.png'),
      items: [
        { id: 11, name: 'Carrot', image: require('./images/carrots.jpg') },
        { id: 12, name: 'Broccoli', image: require('./images/broccoli.jpg') },
      ],
    },
    {
      id: 2,
      name: 'Fruits',
      image: require('./images/fruits.jpeg'),
      items: [
        { id: 21, name: 'Apple', image: require('./images/apple.jpg') },
        { id: 22, name: 'Banana', image: require('./images/banana.jpeg') },
        { id: 23, name: 'Kiwi', image: require('./images/Kiwi.jpg') },
        { id: 24, name: 'orange', image: require('./images/orange.jpg') },
        { id: 25, name: 'pineapple', image: require('./images/pineapple.jpg') },
        { id: 26, name: 'pomegranate', image: require('./images/pomegranate.jpg') },
        { id: 27, name: 'anjou pear', image: require('./images/anjou_pear.jpg') },
        { id: 28, name: 'black berry', image: require('./images/black_berry.jpg') },
        { id: 29, name: 'black grapes', image: require('./images/pomegranate.jpg') },
        { id: 30, name: 'blueberry', image: require('./images/blueberry.jpg') },
        { id: 31, name: 'custard apple', image: require('./images/custard_apple.jpg') },
        { id: 32, name: 'DragonFruit', image: require('./images/DragonFruit.jpg') },
        { id: 33, name: 'green grapes', image: require('./images/green_grapes.jpg') },
        { id: 34, name: 'guava', image: require('./images/guava.jpg') },
        { id: 35, name: 'jackfruit', image: require('./images/jackfruit.jpg') },
        { id: 36, name: 'lemon', image: require('./images/lemon.jpg') },
        { id: 37, name: 'mango', image: require('./images/mango.jpg') },
        { id: 38, name: 'papaya', image: require('./images/papaya.jpg') },
        { id: 39, name: 'peach', image: require('./images/peach.jpg') },
        { id: 40, name: 'rasberry', image: require('./images/rasberry.jpg') },
        { id: 41, name: 'red grapes', image: require('./images/red_grapes.jpg') },
        { id: 42, name: 'star fruit', image: require('./images/star_fruit.jpg') },
        { id: 43, name: 'strawberry', image: require('./images/strawberry.jpg') },
      ],
    },
    {
      id: 3,
      name: 'Accessories',
      image: require('./images/Electronics.jpg'),
      items: [
        { id: 21, name: 'Mirco-Oven', image: require('./images/MicroOven.jpg') },
        { id: 22, name: 'Fridge', image: require('./images/fridge.jpg') },
      ],
    },
  ]
